### ISSUE TITLE
Split repository and rename entities

### ISSUE THREAD

**Issue by mariyadavydova** [neuromation/cookbook#8]
If we assume that our customers will use them as starting points, then forking a repo is much more convenient than copy-pasting code. Also, having them in separate repositories makes community contributing easier. 

Let's stick to 'ML Recipe' and 'Cookbook' terminology from now on for an individual project and a collection, respectively.

So, I suggest to do the following:

* [x] Put each recipe in a separate repository called 'ml-recipe-XXX'.
* [x] Rename this repository to 'cookbook'.
* [x] Make other repositories submodules, tracking head of master branches.
* [ ] Update READMEs accordingly.

**Comment by astaff** [comment]
Some readme updates have been made, but the whole suite needs to be tested end to end. @mariyadavydova please do it and make final updates to README. Can be a separate PR. Thanks.
